name: ser_manos
description: 'App de voluntariado para DAMM 2025'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.4.0
  go_router: ^13.0.1
  http: ^1.3.0
  path_provider: ^2.0.0
  path: ^1.8.3
  intl: ^0.19.0
  flutter_svg: ^2.0.10
  flutter_markdown: ^0.6.18
  collection: ^1.17.2
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.5.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  share_plus: ^7.2.1
  firebase_auth: ^5.5.3
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  image_picker: ^1.0.5
  permission_handler: ^11.3.1 # (iOS ≥ 17 pide permiso explícito)

  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.1.2

#  Launch url to maps
  url_launcher: ^6.2.4
  maps_launcher: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.2
  mockito: ^5.4.4
  fake_cloud_firestore: ^3.1.0
  firebase_storage_mocks: ^0.7.0
  firebase_auth_mocks: ^0.14.0
  golden_toolkit: ^0.15.0
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/map_placeholder.png