name: ser_manos
description: 'App de voluntariado para DAMM 2025'
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.0
  go_router: ^13.0.1
  http: ^1.3.0
  intl: ^0.18.1
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/